#index:
#    path: /
#    controller: App\Controller\DefaultController::index

get_contract:
  path: /clean-arch/contract/{contractNumber}
  controller: App\Controller\ContractController::get
  methods: [GET]

terminate_contract:
  path: /clean-arch/contract/{contractNumber}/terminate/{date}
  controller: App\Controller\ContractController::terminate
  methods: [PUT]