#index:
#    path: /
#    controller: App\Controller\DefaultController::index

get_contract:
  path: /clean-arch/contract/{contractNumber}
  controller: App\Controller\ContractController::get
  methods: [GET]

terminate_contract:
  path: /clean-arch/contract/{contractNumber}/terminate/{toDate}
  controller: App\Controller\ContractController::terminate
  methods: [PUT]

book_risk:
  path: /clean-arch/contract/{contractNumber}/object/{objectId}/book-risk/{riskType}
  controller: App\Controller\ObjectController::bookRisk
  methods: [GET]